package model

const (
	COMPLETE_PROFILE_REWARD_AMOUNT        = 1000
	SIGNUP_REWARD_AMOUNT                  = 1000
	SIGNIN_REWARD_AMOUNT                  = 100
	SIGNIN_ADDITIONAL_DAILY_REWARD_AMOUNT = 10
)
