// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.32
// source: user.proto

package user

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_user_proto struct{}

func (drpcEncoding_File_user_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_user_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_user_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_user_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_user_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCUsersClient interface {
	DRPCConn() drpc.Conn

	GetNftCreators(ctx context.Context, in *Empty) (*UsersResponse, error)
}

type drpcUsersClient struct {
	cc drpc.Conn
}

func NewDRPCUsersClient(cc drpc.Conn) DRPCUsersClient {
	return &drpcUsersClient{cc}
}

func (c *drpcUsersClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcUsersClient) GetNftCreators(ctx context.Context, in *Empty) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/user.Users/GetNftCreators", drpcEncoding_File_user_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCUsersServer interface {
	GetNftCreators(context.Context, *Empty) (*UsersResponse, error)
}

type DRPCUsersUnimplementedServer struct{}

func (s *DRPCUsersUnimplementedServer) GetNftCreators(context.Context, *Empty) (*UsersResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCUsersDescription struct{}

func (DRPCUsersDescription) NumMethods() int { return 1 }

func (DRPCUsersDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/user.Users/GetNftCreators", drpcEncoding_File_user_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCUsersServer).
					GetNftCreators(
						ctx,
						in1.(*Empty),
					)
			}, DRPCUsersServer.GetNftCreators, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterUsers(mux drpc.Mux, impl DRPCUsersServer) error {
	return mux.Register(impl, DRPCUsersDescription{})
}

type DRPCUsers_GetNftCreatorsStream interface {
	drpc.Stream
	SendAndClose(*UsersResponse) error
}

type drpcUsers_GetNftCreatorsStream struct {
	drpc.Stream
}

func (x *drpcUsers_GetNftCreatorsStream) SendAndClose(m *UsersResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_user_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
